products/product_app/urls.py
from django.urls import path
# from homework.homework.products.product_app.views import index, add
from product_app.views import index, add

app_name = 'product_app'

urlpatterns = [
    path('', index, name='index'),
    path('add', add, name='add'),
]

products/products/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product_app.urls', namespace='product')),
]

products/product_app/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    UNITS = (
        (1, 'шт.'),
        (2, 'кг.'),
    )

    name = models.CharField(verbose_name='Наименование', max_length=128)
    date = models.DateField(verbose_name='дата поступления')
    price = models.DecimalField(verbose_name='цена', max_digits=8, decimal_places=0, default=0)
    unit = models.IntegerField(verbose_name='единица измерения', choices=UNITS)
    provider = models.CharField(verbose_name='Поставщик', max_length=256, blank=True)

    class Meta:
        verbose_name = "продукт"
        verbose_name_plural = "продукты"

products/product_app/forms.py
from django.forms import ModelForm

from product_app.models import Product
# from homework.homework.products.product_app.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

products/product_app/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponseRedirect
from product_app.forms import ProductForm
from product_app.models import Product
# from homework.homework.products.product_app.forms import ProductForm
# from homework.homework.products.product_app.models import Product

def index(request):
    return render(request, 'product/index.html', {'product': Product.objects.all()})


def add(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    else:
        form = ProductForm()

    return render(request, 'product/form.html', {'form': form})

products/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'file_type_django_icon_130645.ico' %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Geek</title>
</head>
<body>
<div class="container">
    <ul class="nav justify-content-end">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'product:index' %}">Главная</a>
        </li>
    </ul>
    {% block content %}
    {% endblock %}
</div>
{% block js %}
<script src="http://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}
</body>
</html>

products/templates/product/form.html
{% extends 'layout.html' %}
{% load static %}
{% block content %}
<form action="{% url 'product:add' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="card">
        <div class="card-header">Добавить продукт</div>
        <div class="card-body">{{ form.as_p }}</div>
        <div class="card-footer"><input class="form-control btn btn-info" type="submit" value="Добавить"></div>
    </div>
</form>
{% endblock %}

products/templates/product/index.html
{% extends 'layout.html' %}
{% block content %}
<table class="table">
    <tr>
        <th>Название</th>
        <th>Цена</th>
    </tr>
    {% for product in products %}
    <tr>
        <td>{{ product.name }}</td>
        <td>{{ product.price }}</td>
    </tr>
    {% endfor %}
</table>
<a href="{% url 'product:add' %}" class="btn btn-success">Добавить</a>
{% endblock %}